Repository iSirThijs/jungle-gym, pull requests merged in 2021-06, with the labels that each got.

#162 Feature/strapi endpoint koppelen met frontend
  .env.example
  .gitignore
  package-lock.json
  src/lib/Env.js
  src/lib/GameList/GameListCard.svelte
  src/lib/GamePage/MaterialModal.svelte
  src/routes/games/[game].svelte
  src/routes/index.svelte
Labels: task

#145 Feature/homepage
  .env.example
  package-lock.json
  src/app.css
  src/lib/GameList/GameList.svelte
  src/lib/GameList/GameListCard.svelte
  src/lib/GameList/GameListCarousel.svelte
  src/lib/GameList/GameListHighlighted.svelte
  src/routes/index.svelte
  src/routes/spellen/[game].json.ts
  src/routes/spellen/[game].svelte
  src/routes/spellen/_api.ts
  src/routes/spellen/index.json.ts
  src/routes/spellen/index.svelte
Labels: task

#168 Feature/non offline game page
  src/routes/__layout.svelte
  src/routes/spellen/[game].svelte
  src/routes/spellen/__error.svelte
  src/routes/spellen/__layout.svelte
  src/routes/spellen/offline.svelte
  src/service-worker.ts
Labels: blocked, task

#194 Remove branch name from PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: workflow

#193 Feature/redesign overzichtspagina implementeren
  src/app.css
  src/lib/GameList/GameListCard.svelte
  src/lib/assets/icons/GameCard/cardArrow.svg
  src/lib/assets/icons/GameCard/minPlayers.svg
  src/lib/assets/images/background/leavesBackground.svg
  src/lib/shared/Background/LeavesBackground.svelte
  src/lib/shared/Label/CardLabel.svelte
  src/routes/spellen/index.svelte
Labels: task

#199 Redesign header en menu
  src/app.css
  src/routes/__layout.svelte
Labels: task

#224 Added a store to make snackbar reactable
  src/lib/Stores/message.ts
  src/lib/shared/Snackbar/Snackbar.svelte
  src/routes/__layout.svelte
  src/routes/spellen/[game].svelte
  src/routes/spellen/__layout.svelte
Labels: task

#189 Feature/inloggen
  .env.example
  README.md
  package-lock.json
  package.json
  src/hooks.ts
  src/lib/Env.js
  src/lib/Stores/mockUser.ts
  src/lib/Utils/sessionDB.ts
  src/lib/account/LoginForm.svelte
  src/routes/__layout.svelte
  src/routes/account/__layout.svelte
  src/routes/account/index.svelte
  src/routes/account/uitloggen.json.ts
  src/routes/inloggen/index.json.ts
  src/routes/inloggen/index.svelte
Labels: task

#208 Add sort function that will sort the games based on the last updated
  src/lib/GameViews/List.svelte
Labels: task
